name: "Project triage: test"

on:
  issues:
    types: [opened]

jobs:
  check:
    runs-on: ubuntu-latest
    if: "contains( github.event.issue.labels.*.name, 'agency-onboarding')"
    steps:
      - run: echo 'new agency onboarding issue detected'

  inverted-check:
    runs-on: ubuntu-latest
    if: "!contains( github.event.issue.labels.*.name, 'agency-onboarding')"
    steps:
      - run: echo 'new issue detected, not agency onboarding though'
